# Generated by Django 5.2.3 on 2025-07-18 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpcontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('te', 'Telugu')], default='en', max_length=10),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('te', 'Telugu')], default='en', max_length=10),
        ),
    ]
