# Generated by Django 5.2.3 on 2025-07-05 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10)),
                ('language', models.CharField(choices=[('en', 'English'), ('te', 'Telugu'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('ml', 'Malayalam')], default='en', max_length=10)),
                ('is_sound_on', models.BooleanField(default=True)),
                ('is_vibrate_on', models.BooleanField(default=False)),
                ('show_help', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserSettings',
                'verbose_name_plural': 'UserSettings',
            },
        ),
        migrations.DeleteModel(
            name='tools',
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'users', 'verbose_name_plural': 'users'},
        ),
    ]
