# Generated by Django 5.2.3 on 2025-07-05 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersettings_delete_tools_alter_users_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('te', 'Telugu'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('it', 'Italian')], default='en', max_length=10)),
            ],
            options={
                'verbose_name': 'HelpContent',
                'verbose_name_plural': 'HelpContent',
            },
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('te', 'Telugu'), ('hi', 'Hindi'), ('ta', 'Tamil'), ('kn', 'Kannada'), ('ml', 'Malayalam'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('it', 'Italian')], default='en', max_length=10),
        ),
    ]
