# Generated by Django 5.2.3 on 2025-07-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_userprofile_email_remove_userprofile_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpcontent',
            options={'verbose_name': 'Help Content', 'verbose_name_plural': 'Help Contents'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile', 'verbose_name_plural': 'User Profiles'},
        ),
        migrations.AlterModelOptions(
            name='usersettings',
            options={'verbose_name': 'User Settings', 'verbose_name_plural': 'User Settings'},
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='is_sound_on',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='is_vibrate_on',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='show_help',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
