# Generated by Django 5.2.3 on 2025-07-16 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tools_viewed', models.PositiveIntegerField(default=0)),
                ('total_reviews_given', models.PositiveIntegerField(default=0)),
                ('total_favourites', models.PositiveIntegerField(default=0)),
                ('total_feedbacks', models.PositiveIntegerField(default=0)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
                ('last_active_tool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tools.tool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favourites',
                'verbose_name_plural': 'Favourites',
            },
        ),
        migrations.CreateModel(
            name='ToolOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
            ],
            options={
                'verbose_name': 'Favourites',
                'verbose_name_plural': 'Favourites',
            },
        ),
    ]
