# Generated by Django 5.2.3 on 2025-07-16 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'Tool', 'verbose_name_plural': 'Tools'},
        ),
    ]
